theme: jekyll-theme-leap-day
title: "The Conversational Intelligence Challenge"
description: "Competitive human evaluation of existing dialogue systems and collection of rated dialogs for future training of end-to-end systems"
