theme: jekyll-theme-minimal
title: "The Conversational Intelligence Challenge"
description: "Competitive human evaluation of existing dialogue systems and crowdsourcing of rated dialogs for future training of end-to-end systems"
